### ISSUE TITLE
Error on user registration

### ISSUE THREAD

**Issue by reliaboe** [mimir-org/typelibrary#177] opened 2022-09-27 07:22 UTC
If you have created a none valid schema in user registration, nothing happend on the second try. You have to refresh the page. This happens in dev environment.

I tried to regigister a user with not valid password. First there is a message with none valid password length. I replace the password, and nothing happens. None call to backend application.

**Comment by Fruithut** [comment] 2022-09-27 11:07
Having some trouble reproducing this issue @reliaboe.
If I replace both password fields with a valid password after getting an error for them I am still able to submit 🤔

**Comment by Fruithut** [comment] 2022-10-19 20:19
Closing this issue since the registration flow is being reimplemented with #81 💡

**Closed by Fruithut** 2022-10-19 20:19 UTC
Labels: bug
